language: node_js  #设置语言

node_js: 
  - 12 #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成
  - hexo d  #发布

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/shuishuixiong/shuishuixiong.github.io.git  #设置GH_REF，注意更改yourname

notifications:
  email:
    on_success: always
    on_failure: always